### ISSUE TITLE
Bluetooth connection issue in iOS

### ISSUE THREAD

**Issue by reinarrow** [lidiapb/moonboard#4]
iOS devices are not able to connect to the system. When trying, the phone asks for pairing (which is not expected). Clicking on yes or no both produce an unsuccessful connection.

**Comment by reinarrow** [comment]
BLE advertising flag: BR/EDR Not Supported (to avoid complex pairing to be attempted)

**Comment by reinarrow** [comment]
https://stackoverflow.com/questions/28307555/how-to-force-bluetooth-le-just-works-pairing-in-android

**Comment by reinarrow** [comment]
https://jimmywongiot.com/2019/08/13/advertising-payload-format-on-ble/


Looks useful. Try bit 2 of Flags advertising to 0.

**Comment by reinarrow** [comment]
> https://jimmywongiot.com/2019/08/13/advertising-payload-format-on-ble/
> 
> Looks useful. Try bit 2 of Flags advertising to 0.

Not so useful. The original code already set that flag as expected (BR/EDR is set as not supported in advertising)

**Comment by reinarrow** [comment]
https://stackoverflow.com/questions/59214524/since-bluez-5-48-iphones-require-pairing-when-connecting-on-a-ble-gap-periphera
This seems to be the root of the issue. Is is a known bug with a bluez update (battery module). Will test workarounds from the last response.

**Comment by reinarrow** [comment]
> https://stackoverflow.com/questions/59214524/since-bluez-5-48-iphones-require-pairing-when-connecting-on-a-ble-gap-periphera
> This seems to be the root of the issue. Is is a known bug with a bluez update (battery module). Will test workarounds from the last response.

Tried the two solutions from the latest response in this question. The custom agent did not work (broke connection even for Android), but **disabling the battery plugin in bluetooth.service did the trick**. No more PIN is requested. Need to investigate how to do it from the install script,

**Comment by reinarrow** [comment]
@smai86 I have just pushed a hotfix to master where the install script automatically disables the offending module from bluez. If you can test it please let me know if it fixes your problems.

**Comment by smai86** [comment]
@lidiapb Perfect, thanks! I edited the bluetooth.service and now it works! Thanks for your help!!! (Tried with my iPhone 12 Pro with iOS 14.6)

But I have an other small question and maybe you could help... I edited a few lines and files, because I only used every 5th LED. Its all working fine, but when i enable the LED Test it crashes on bootup. Do you have an idea how i could enable the test in my case?

EDIT: I´ve edited the led_mapping.json file for my LED Setup, do I have to edit the numbers in the moonboard.py file also?
